import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'instance.freezed.dart';

part 'instance.g.dart';

@freezed
class Instance with _$Instance {
  const factory Instance({
    required int id,
    required String domain,
    required String published,
    String? updated,
    String? software,
    String? version,
  }) = _Instance;

  factory Instance.fromJson(Map<String, Object?> json) => _$InstanceFromJson(json);
}
