import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:lemmy_is_api/src/lemmy_is_api.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'create_comment_like.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'create_comment_like.g.dart';

@freezed
class CreateCommentLike with _$CreateCommentLike, hasToJson {
  const factory CreateCommentLike({@JsonKey(name: "comment_id") required int commentId, required int score}) = _CreateCommentLike;

  factory CreateCommentLike.fromJson(Map<String, Object?> json) => _$CreateCommentLikeFromJson(json);
}
