import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:lemmy_is_api/src/lemmy_is_api.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'create_post_like.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'create_post_like.g.dart';

@freezed
class CreatePostLike with _$CreatePostLike, hasToJson {
  const factory CreatePostLike({@JsonKey(name: "post_id") required int postId, required int score}) = _CreatePostLike;

  factory CreatePostLike.fromJson(Map<String, Object?> json) => _$CreatePostLikeFromJson(json);
}
