import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:lemmy_is_api/src/lemmy_is_api.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'get_person.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'get_person.g.dart';

@freezed
class GetPerson with _$GetPerson, hasToJson {
  const factory GetPerson({
    @JsonKey(name: "community_id") int? communityId,
    int? limit,
    int? page,
    @JsonKey(name: "person_id") int? personId,
    @JsonKey(name: "saved_only") bool? savedOnly,
    @JsonKey(name: "sort") String? rawSort,
    String? username,
  }) = _GetPerson;

  factory GetPerson.fromJson(Map<String, Object?> json) => _$GetPersonFromJson(json);
}
