import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:lemmy_is_api/src/lemmy_is_api.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'get_site_metadata.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'get_site_metadata.g.dart';

@freezed
class GetSiteMetadata with _$GetSiteMetadata, hasToJson {
  const factory GetSiteMetadata({
    required String url,
  }) = _GetSiteMetadata;

  factory GetSiteMetadata.fromJson(Map<String, Object?> json) => _$GetSiteMetadataFromJson(json);
}
