import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:lemmy_is_api/src/lemmy_is_api.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'get_comment.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'get_comment.g.dart';

@freezed
class GetComment with _$GetComment, hasToJson {
  const factory GetComment({
    @JsonKey(name: "id") required int commentId,
  }) = _GetComment;

  factory GetComment.fromJson(Map<String, Object?> json) => _$GetCommentFromJson(json);
}
