import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:lemmy_is_api/src/lemmy_is_api.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'get_posts.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'get_posts.g.dart';

@freezed
class GetPosts with _$GetPosts, hasToJson {
  const GetPosts._();

  const factory GetPosts({
    @JsonKey(name: "community_name") String? communityName,
    @JsonKey(name: "community_id") int? communityId,
    int? limit,
    int? page,
    @JsonKey(name: "saved_only") bool? savedOnly,
    @JsonKey(name: "sort") String? rawSort,
    @JsonKey(name: "type") String? rawType,
  }) = _GetPosts;

  factory GetPosts.fromJson(Map<String, Object?> json) => _$GetPostsFromJson(json);
}
