import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:lemmy_is_api/src/lemmy_is_api.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'get_community.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'get_community.g.dart';

@freezed
class GetCommunity with _$GetCommunity, hasToJson {
  const factory GetCommunity({int? id, String? name}) = _GetCommunity;

  factory GetCommunity.fromJson(Map<String, Object?> json) => _$GetCommunityFromJson(json);
}
