import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:lemmy_is_api/src/lemmy_is_api.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'get_replies.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'get_replies.g.dart';

@freezed
class GetReplies with _$GetReplies, hasToJson {
  const factory GetReplies({String? sort, int? number, int? limit, @JsonKey(name: "unread_only") bool? unreadOnly}) = _GetReplies;

  factory GetReplies.fromJson(Map<String, Object?> json) => _$GetRepliesFromJson(json);
}
