import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:lemmy_is_api/src/lemmy_is_api.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'list_communities.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'list_communities.g.dart';

@freezed
class ListCommunities with _$ListCommunities, hasToJson {
  const factory ListCommunities({
    bool? show_nsfw,
    int? limit,
    int? page,
    @JsonKey(name: "saved_only") bool? savedOnly,
    String? sort,
    @JsonKey(name: "type_") String? type,
  }) = _ListCommunities;

  factory ListCommunities.fromJson(Map<String, Object?> json) => _$ListCommunitiesFromJson(json);
}
