import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:lemmy_is_api/src/lemmy_is_api.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'login.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'login.g.dart';

@freezed
class Login with _$Login, hasToJson {
  const factory Login({
    @JsonKey(name: "username_or_email") required String usernameOrEmail,
    required String password,
  }) = _Login;

  factory Login.fromJson(Map<String, Object?> json) => _$LoginFromJson(json);
}
