import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:lemmy_is_api/src/lemmy_is_api.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'save_user_settings.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'save_user_settings.g.dart';

@freezed
class SaveUserSettings with _$SaveUserSettings, hasToJson {
  const factory SaveUserSettings({
    bool? show_nsfw,
    bool? blur_nsfw,
    bool? auto_expand,
    bool? show_scores,
    String? theme,
    String? default_sort_type,
    String? efault_listing_type,
    String? interface_language,
    String? avatar,
    String? banner,
    String? display_name,
    String? email,
    String? bio,
    String? matrix_user_id,
    bool? show_avatars,
    bool? send_notifications_to_email,
    bool? bot_account,
    bool? show_bot_accounts,
    bool? show_read_posts,
    bool? show_new_post_notifs,
    bool? discussion_languages,
    bool? generate_totp_2fa,
    bool? open_links_in_new_tab,
    bool? infinite_scroll_enabled,
  }) = _SaveUserSettings;

  factory SaveUserSettings.fromJson(Map<String, Object?> json) => _$SaveUserSettingsFromJson(json);
}
