import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:lemmy_is_api/src/lemmy_is_api.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'save_post.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'save_post.g.dart';

@freezed
class SavePost with _$SavePost, hasToJson {
  const factory SavePost({
    @JsonKey(name: "post_id") required int postId,
    required bool save,
  }) = _SavePost;

  factory SavePost.fromJson(Map<String, Object?> json) => _$SavePostFromJson(json);
}
