import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:lemmy_is_api/src/lemmy_is_api.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'save_comment.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'save_comment.g.dart';

@freezed
class SaveComment with _$SaveComment, hasToJson {
  const factory SaveComment({
    @JsonKey(name: "comment_id") required int commentId,
    required bool save,
  }) = _SaveComment;

  factory SaveComment.fromJson(Map<String, Object?> json) => _$SaveCommentFromJson(json);
}
