import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:lemmy_is_api/src/lemmy_is_api.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'search.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'search.g.dart';

@freezed
class Search with _$Search, hasToJson {
  const factory Search({
    @JsonKey(name: "q") required String query,
    @JsonKey(name: "community_id") int? communityId,
    @JsonKey(name: "community_name") String? communityName,
    @JsonKey(name: "creator_id") int? creatorId,
    @JsonKey(name: "type_") String? type,
    String? sort,
    @JsonKey(name: "listing_type") String? listingType,
    int? page,
    int? limit,
  }) = _Search;

  factory Search.fromJson(Map<String, Object?> json) => _$SearchFromJson(json);
}
