/*{
  "comment": {
    "id": 807884,
    "creator_id": 546532,
    "post_id": 1035038,
    "content": "Who's Lenny?",
    "removed": false,
    "published": "2023-07-07T11:08:36.267008",
    "deleted": false,
    "ap_id": "https://lemmy.world/comment/930944",
    "local": false,
    "path": "0.807884",
    "distinguished": false,
    "language_id": 0
  },
  "creator": {
    "id": 546532,
    "name": "Teriyakiboy98",
    "avatar": "https://lemmy.world/pictrs/image/6289733f-efa5-4d8c-9bc2-b969ada60572.png",
    "banned": false,
    "published": "2023-06-20T11:13:59.790344",
    "actor_id": "https://lemmy.world/u/Teriyakiboy98",
    "local": false,
    "banner": "https://lemmy.world/pictrs/image/4012e390-06c8-479a-ab13-af5e231447c5.png",
    "deleted": false,
    "admin": false,
    "bot_account": false,
    "instance_id": 96772
  },
  "post": {
    "id": 1035038,
    "name": "{M} New Lenny account gotta give a free booty pic",
    "body": "![](https://lemmynsfw.com/pictrs/image/78b5edfe-3cd2-4442-8906-aa7af76251ff.jpeg)",
    "creator_id": 1023888,
    "community_id": 28272,
    "removed": false,
    "locked": false,
    "published": "2023-07-07T03:59:46.412742",
    "deleted": false,
    "nsfw": true,
    "ap_id": "https://lemmynsfw.com/post/217962",
    "local": false,
    "language_id": 0,
    "featured_community": false,
    "featured_local": false
  },
  "community": {
    "id": 28272,
    "name": "gonewild",
    "title": "gonewild",
    "description": "Not unlike redditâs community, but unaffiliated to them. A refuge for those who have been disappointed in their refusal of a blackout. Gonewild is a place for open-minded adults to exchange their nude bodies for karma; showing it off in a comfortable environment without pressure.\n\n  1. /c/gonewild is for posting visibly nude photos of **yourself**.\n  2. Abusive, rude, or troll behavior is not permitted.\n  3. Tag your post titles with the correct gender tag - **[f], [m], [cd], [t], [?], [nb]**\n  4. No asking for upvotes (directly or indirectly).\n  5. Do not feed the trolls.\n  6. No name guessing or attempts to identify someone.\n  7. No mentioning or pestering for off-site contact (snapchat,OF, kik, tumblr, twitter, IG, PornHub, wishlists, etc.)\n  8. Do not delete your verification post\n\nThis is not a community for advertisement, just for posting nudes.\n\nRespect the anonymity of our users or be banned. If you link to another userâs personal info/content outside Lemmy - if you so much as try to guess a name - you will be shown the door.\n\nConsent is a critical part of the overall health of this community. You may be required to submit verification and prove youâre the one in the photos\nReport any comments or threads you find abusive. We check the reported queue often. If you come across a user being mean spirited or posting personal info, click the report link.\n\nWhen you argue with a troll, you are entering a competition to see who has more free time. You will lose, because you have a life and the troll does not. Do not EVER respond to trolls. Instead, report them!",
    "removed": false,
    "published": "2023-06-12T11:58:45.890262",
    "updated": "2023-07-06T01:11:47.445179",
    "deleted": false,
    "nsfw": true,
    "actor_id": "https://lemmynsfw.com/c/gonewild",
    "local": false,
    "hidden": false,
    "posting_restricted_to_mods": false,
    "instance_id": 97073
  },
  "counts": {
    "id": 671259,
    "comment_id": 807884,
    "score": 2,
    "upvotes": 2,
    "downvotes": 0,
    "published": "2023-07-07T11:08:36.267008",
    "child_count": 0,
    "hot_rank": 787
  },
  "creator_banned_from_community": false,
  "subscribed": "NotSubscribed",
  "saved": false,
  "creator_blocked": false
},*/